# Application config parameters:

#logging.level.root=INFO
#logging.level.webfilter=WARN
#logging.level.app=WARN

ext.services.service-b.timeouts.connection.millis=5000
ext.services.service-b.timeouts.read.millis=5000

#spring.cache.jcache.config=classpath:ehcache.xml
cache.heap.entries=2
cache.persistence.size=1
cache.persistence.unit=MB
cache.persistence.path=/tmp/ehcache
cache.expiry.ttl.seconds=5
cache.expiry.idle.seconds=10

pg.db.url=jdbc:postgresql://localhost:5432/mydatabase
pg.db.username=admin
pg.db.password=password

