# Application config parameters:

logging.level.root=INFO
logging.level.app=INFO
logging.level.webfilter=DEBUG

pg.db.url=jdbc:postgresql://localhost:5432/mydatabase
pg.db.username=admin
pg.db.password=password
