#spring.config.activate.on-profile=dev | qa | test | staging | prod



# MANDATORY in user configuration on the command line

# pg.db.url=
# pg.db.username=
# pg.db.password=



# OPTIONAL with default values

#spring.cache.jcache.config=classpath:ehcache.xml
cache.heap.entries=2
cache.persistence.size=1
cache.persistence.unit=MB
cache.persistence.path=${java.io.tmpdir:/tmp}/ehcache
cache.expiry.ttl.seconds=5
cache.expiry.idle.seconds=10

ext.services.service-b.timeouts.connection.millis=5000
ext.services.service-b.timeouts.read.millis=5000
