#spring.config.activate.on-profile=dev | qa | test | staging | prod



# MANDATORY in user configuration on the command line

# pg.db.url=
# pg.db.username=
# pg.db.password=



# OPTIONAL with default values

#spring.cache.jcache.config=classpath:ehcache.xml
cache.heap.entries=2
cache.persistence.size=1
cache.persistence.unit=MB
cache.persistence.path=${java.io.tmpdir:/tmp}/ehcache
cache.expiry.ttl.seconds=5
cache.expiry.idle.seconds=10

ext.services.service-b.timeouts.connection.millis=5000
ext.services.service-b.timeouts.read.millis=5000

default.logging.level.root=INFO
default.logging.level.app=DEBUG
default.logging.level.webfilter=TRACE
dev.logging.level.root=INFO
dev.logging.level.app=ALL
dev.logging.level.webfilter=TRACE
prod.logging.level.root=ERROR
prod.logging.level.app=WARN
prod.logging.level.webfilter=ERROR
other.logging.level.root=WARN
other.logging.level.app=INFO
other.logging.level.webfilter=TRACE
non-dev.logging.exception-conversion-word=%.-1000replace(%exception{3}){'[\r\n\t]+', '  '}%nopex
# Single line. Full stack trace will be captured in a single line.
#logging.exception-conversion-word=%replace(%wEx){'\n','\u2028'}%nopex
# Truncated Single line. Only the exception message will be captured in a single line.
#logging.exception-conversion-word=%replace(%wEx{short}){'\n','\u2028'}%nopex
# Truncated. Default formatting but only capturing a single line.
#logging.exception-conversion-word=%wEx{short}
#LOG_EXCEPTION_CONVERSION_WORD
dev.logging.exception-conversion-word=%wEx{\
    full, \
    java.lang.reflect.Method, \
    io.undertow, \
    org.apache.tomcat, \
    org.apache.catalina, \
    org.apache.coyote, \
    org.springframework.aop, \
    org.springframework.security, \
    org.springframework.transaction, \
    org.springframework.web, \
    org.springframework.cglib, \
    org.springframework.boot, \
    rx.internal, \
    rx.Observable, \
    com.google.gson.internal, \
    java.util.concurrent, \
    sun.reflect, \
    net.sf.cglib, \
    ByCGLIB \
}
logging.include-application-name=true
logging.include-application-group=true
logging.register-shutdown-hook=true
